services:
  postgres:
    image: postgres:16
    container_name: cars-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cars
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: cars
    volumes:
      - cars-postgres-data:/var/lib/postgresql/data

volumes:
  cars-postgres-data:
